export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DETAIL_PRODUCT = "DETAIL_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CLEAR_ALL_PRODUCT = "CLEAR_ALL_PRODUCT";
